# -*- coding: utf-8 -*-
"""televisores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CsJiZ36elmsYaAPXzwBdafWjjC-nyS6K
"""

class Marca:
  def __init__(self, nombre):
    self.nombre=nombre

  def getNombre(self):
    return self.nombre
  def setNombre(self, nombre):
    self.nombre=nombre
 
class TV:
  numTV=0
  def __init__(self,marca,estado):
    self.marca=marca
    self.canal=1
    self.precio=500
    self.estado=estado
    self.volumen=1
    self.control=None
    TV.numTV+=1        
  
  def setNumTV(numTV):
    TV.numTV=numTV
  def getNumTV():
    return TV.numTV

  def setMarca(self, marca):
    self.marca=marca
  def getMarca(self):
    return self.marca

  def setControl(self, control):
    self.control=control
  def getControl(self):
    return self.control

  def setPrecio(self, precio):
    self.precio=precio
  def getPrecio(self):
    return self.precio

  def setVolumen(self, volumen):
    if self.volumen>=0 and self.volumen<=7 and self.estado==True:
      self.volumen=volumen
  def getVolumen(self):
    return self.volumen

  def setCanal(self, canal):
    if canal>=1 and canal<=120 and self.estado==True:
      self.canal=canal
  def getCanal(self):
    return self.canal

  def turnOn(self):
    self.estado=True
  def turnOff(self):
    self.estado=False

  def getEstado(self):
    return self.estado

  def canalUp(self):
    if self.canal>=1 and self.canal<120 and self.estado==True:
      self.canal+=1
  def canalDown(self):
    if self.canal>1 and self.canal<=120 and self.estado==True:
      self.canal-=1
  def volumenUp(self):
    if self.volumen>=0 and self.volumen<7 and self.estado==True:
      self.volumen+=1
  def volumenDown(self):
    if self.volumen>=0 and self.volumen<7 and self.estado==True:
      self.volumen-=1

class Control:
  def __init__(self):
    self.tv=None
  
  def turnOn(self):
    self.tv.estado=True
  def turnOff(self):
    self.tv.estado=False

  def canalUp(self):
    if self.tv.canal>=1 and self.tv.canal<120 and self.tv.estado==True:
      self.tv.canal+=1
  def canalDown(self):
    if self.tv.canal>1 and self.tv.canal<=120 and self.tv.estado==True:
      self.tv.canal-=1

  def volumenUp(self):
    if self.tv.volumen>=0 and self.tv.volumen<7 and self.tv.estado==True:
      self.tv.volumen+=1
  def volumenDown(self):
    if self.tv.volumen>=0 and self.tv.volumen<7 and self.tv.estado==True:
      self.tv.volumen-=1
  
  def setCanal(self, canal):
    if canal>=1 and canal<=120 and self.tv.estado==True:
      self.tv.canal=canal

  def enlazar(self,tv):
    self.tv=tv
    tv.setControl(self)

  def getTv(self):
    return self.tv
  def setTv(self, tv):
    self.tv=tv